import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import Footer from '../components/footer';
import Header from '../components/header';
import Users from '../components/users';
import { UserResponse } from '../interfaces/User';

export default function Home() {
  const [user, setUser] = useState<UserResponse | null>({} as UserResponse);
  const router = useRouter();

  useEffect(() => {
    const data = localStorage.getItem('user');

    if (!data) {
      router.push('/login');
    }

    const parsedData = JSON.parse(data as string);

    if(!parsedData?.id || !parsedData?.name || !parsedData?.username || !parsedData?.password || !parsedData?.faceBase64) {
      router.push('/login');
    }

    setUser(parsedData);
  }, [router]);

  return (
    <div className='container'>
      <Header />

      <Head>
        <title>Face Recognition authorization</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Users currUser={user!} />

      <Footer />
    </div>
  )
}
