import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import Footer from '../components/footer';
import Header from '../components/header';
import Users from '../components/users';

export default function Home() {
  const [v, setV] = useState(0);
  const router = useRouter();
  useEffect(() => {
    const user = localStorage.getItem('user');

    if (!user) {
      router.push('/login');
    }
  }, [router]);

  return (
    <div className='container'>
      <Header />

      <Head>
        <title>Face Recognition authorization</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Users setV={setV} />

      <Footer />
    </div>
  )
}
