import Head from 'next/head';
import Header from '../components/header';
import { useRouter } from 'next/router';
import { useEffect, useRef } from 'react';
import Login from '../components/login';
import Footer from '../components/footer';

export default function Home() {
    const router = useRouter();
    const videoRef = useRef<HTMLVideoElement>(null);
    const canvasRef = useRef<HTMLCanvasElement>(null);

    const startVideo = async () => {
        if (navigator.mediaDevices.getUserMedia) {
            try {
                const stream = await navigator.mediaDevices.getUserMedia({ video: true });

                if(!videoRef.current) {
                    return;
                }

                videoRef.current.srcObject = stream;

                videoRef.current.pause();
                setTimeout(() => {
                    videoRef.current!.play();
                }, 150);

            } catch (error) {
                console.log("Something went wrong!", error);
            }
        }
    };

    useEffect(() => {
        const user = localStorage.getItem('user');

        if (user) {
            router.push('/');
        }

        startVideo();
    }, [router]);

  return (
    <div className='container'>
      <Header />
      
      <Head>
        <title>Face Recognition authorization</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login videoRef={videoRef} canvasRef={canvasRef} router={router} />

      <Footer />
    </div>
  )
}
